### ISSUE TITLE
"Show as many comments as possible on a page" not working any more

### ISSUE THREAD

**Issue by daroczig** [Ajnasz/Hupper-for-Chromium#3]
First of all, thanks for that nice piece of extension that I use with [Chrome](https://chrome.google.com/webstore/detail/hupper/gpgbdmgjfdfjkfgogmfokkmfoacbdghj/details?hl=en). Until now, the awesome feature to show all comments worked like a charm, but it stopped working somehow in the last few days. Any ideas? Now the extension is not adding the `?comments_per_page=9999` suffix to the URLs, but e.g. the sidebar widget actions  (minimalize, reorder) do work.

**Comment by daroczig** [comment]
It seems this happens only with [polls](http://hup.hu/poll), normal and blog posts still works like a charm.

**Comment by Ajnasz** [comment]
Hi!

I didn't touch the extension for a long time, but now I'm on it. Lot of things changed since, so first I need to update the manifest.json and apply new security polociies. I already started it yesterday and almost done. When I finished that I'm going to fix that issue and release a new version together with the other modifications.

Hopefully I can do that today!

**Comment by daroczig** [comment]
Awesome, thank you very much. Please let me know if I could help with anything (e.g. testing).

**Comment by Ajnasz** [comment]
Fixed it and you should be able to update now!

**Comment by daroczig** [comment]
And works like a charm :)
Thank you a thousand times!
